Return-path: <linux-media-owner@vger.kernel.org>
Received: from mail-wi0-f178.google.com ([209.85.212.178]:64356 "EHLO
	mail-wi0-f178.google.com" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
	with ESMTP id S932996Ab3BOKys (ORCPT
	<rfc822;linux-media@vger.kernel.org>);
	Fri, 15 Feb 2013 05:54:48 -0500
Received: by mail-wi0-f178.google.com with SMTP id o1so966286wic.17
        for <linux-media@vger.kernel.org>; Fri, 15 Feb 2013 02:54:47 -0800 (PST)
MIME-Version: 1.0
In-Reply-To: <1554138.lFCgcHDuOa@avalon>
References: <CAJRKTVoKYyJqP1mE=HTmm2jq9uoSkX9kf0HcMxz7F9wZnD1Y5w@mail.gmail.com>
 <CAJRKTVpcBfyYfbdC-+DL2UgtDR=KNRO87a+Uch583sU=8h70CQ@mail.gmail.com>
 <CAJRKTVruizr6AZJk6i8nbG0VE_9iCtNg8y5XCDvJPTnEq9uhAQ@mail.gmail.com> <1554138.lFCgcHDuOa@avalon>
From: Adriano Martins <adrianomatosmartins@gmail.com>
Date: Fri, 15 Feb 2013 08:54:27 -0200
Message-ID: <CAJRKTVq2yp93Dp3wTomHON8DP4RNxRQYQtY9DzuHRiSsKdSCnA@mail.gmail.com>
Subject: Re: omap3isp IRQs
To: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
Cc: linux-media <linux-media@vger.kernel.org>
Content-Type: text/plain; charset=ISO-8859-1
Sender: linux-media-owner@vger.kernel.org
List-ID: <linux-media.vger.kernel.org>

Hi Laurent,

2013/2/14 Laurent Pinchart <laurent.pinchart@ideasonboard.com>:
> On Thursday 14 February 2013 17:17:40 Adriano Martins wrote:
>> 2013/2/13 Adriano Martins <adrianomatosmartins@gmail.com>:
>> > 2013/2/13 Adriano Martins <adrianomatosmartins@gmail.com>:
>> >> Hi,
>> >>
>> >> Please, help me :-)
>> >>
>> >> I trying capture frames from my new sensor, ov5640. I already capture
>> >> images from a mt9p031 camera, but I have some problems with ov5640.
>> >>
>> >> Someone can explain me what are the CCDC_VD0_IRQ and CCDC_VD1_IRQ?
>
> Those two interrupts are generated by the CCDC using programmable line
> counters. The ISP driver programs the CCDC to generate the VD0 interrupt on
> the last line of the image and the VD1 interrupt at 2/3 of the image.

Ok, I understand now. :-)

>> >> In the mt9p031 sensor, I get all interrupts (including HS_VS_IRQ) and
>> >> I can capture frames.
>> >>
>> >> In other sensor, I can't capture any frame. I get many HS_VS_IRQ only,
>> >> then yavta app hangs and I need stop it. Then I get CCDC stop timeout!
>> >> Is it necessary get CCDC_VD0_IRQ and CCDC_VD1_IRQ ever to capture a
>> >> frame?
>
> Yes. A failure to get them usually indicates that the number of lines
> generated by the sensor doesn't match the number of lines expected by the CCDC
> (possibly because the HS signal is completely missing).

Correct. I had hardware problems. The HS signal was unconnected.

>> >> I think all signal from ov5640 sensor are ok. A question about it:
>> >> vsync may be in high level until the frame is transmitted? On my case
>> >> I see just a pulse of vsync before hsync pulses. Is it correct?
>> >
>> > I can capture frames now, and get all interrupts.
>> > But, The image has only green color.
>>
>> I solved my problem. The .data_lane_shift and yuv sequence were wrong.
>
> Glad to know you've solved the problem :-)
>
>> > I have configured the CCDC module as V4L2_MBUS_FMT_UYVY8_2X8, and the
>> > sensor output format is configured as YUV422 with sequence UYVY.
>> >
>> > somebody has any idea?

Thanks

Regards
Adriano Martins
